### PR TITLE
Keep stats of logins by 2FA type.

### PR DESCRIPTION
**Pull request by dd32**
See https://github.com/WordPress/wporg-two-factor/issues/20#issuecomment-2256101255

### CODE REVIEW

**Comment by dd32** [comment]
Added and backfilled what I could for the stat from the current user sessions. Doesn't account for users who used logout.

**Review by pkevan — COMMENTED** [review]
👍

**Comment by pkevan** [comment]
> Added and backfilled what I could for the stat from the current user sessions. Doesn't account for users who used logout.

Was wondering how the stats had historical data - thanks for mentioning!

**Comment by dd32** [comment]
I was going to wait for a review, but then found the partial historical data and just went with it :)

Partial data is better than nothing, and will at least allow a bit more of a baseline for the next month.

**Pull request merged**
