### PR TITLE
Clear notice when inputs array is empty on TOTP screen

### LINKED ISSUE #106: Scan QR Code - Clearing input should remove error state.
When the inputs are cleared, the error state should  be cleared.

## Screenshot
Screenshot 2023-04-18 at 1 34 48 PM

## Test
1. Enter random digits
2. Notice all the fields go red
3. Clear all inputs, notice they are still red.

### PR DESCRIPTION
**Pull request by outdoor2kode**
Fixes #106 

## Screenshot

clear error notice

### CODE REVIEW

**Comment by StevenDufresne** [comment]
Does it make sense to clear the error state once they remove the last value?

**Comment by outdoor2kode** [comment]
> Does it make sense to clear the error state once they remove the last value?

We could, but it's probably that someone somehow deletes the first digit first, likely an edge case, though.

If we're looking to not iterate the whole array every time, logic like `! inputs.some( input => input !== '')` would work, but it's a bit convoluted. And I guess it's ok to iterate for only 6 digits with only entering the condition when there's an error.

**Comment by StevenDufresne** [comment]
> We could, but it's probably that someone somehow deletes the first digit first, likely an edge case, though.

Not the first digit, the last one, so as the user is reversing their changes, as soon as we get to:

```
[ 1 ] [ 2 ] [ 3 ] [ 4 ] [ 5 ] [ 7 ] <-- error shown
[ 1 ] [ 2 ] [ 3 ] [ 4 ] [ 5 ] [   ] <-- remove error state
[ 1 ] [ 2 ] [ 3 ] [ 4 ] [   ] [   ]
...
```

remove the error messages since it's technically not incorrect anymore.

**Comment by outdoor2kode** [comment]
> Not the first digit, the last one, so as the user is reversing their changes, as soon as we get to:

Ah, thanks for the clarification! Sorry for not fully understanding your idea at the beginning.

**Update Gif**

Screen Capture on 2023-04-21 at 11-30-41

**Review by StevenDufresne — APPROVED** [review]
I _think_ this works. 

More people using 2fa will help inform this better so I vote we merge this and ask for more general feedback later.

**Pull request merged**
