### PR TITLE
Fix TOTP mobile incorrect look

### PR DESCRIPTION
**Pull request by outdoor2kode**
Ref: https://github.com/WordPress/wporg-two-factor/pull/112#issuecomment-1515590278

## Results

https://user-images.githubusercontent.com/18050944/233264557-8d9be3d8-2049-4b87-9972-9368f6d326a2.mp4

Screen Shot 2023-04-20 at 1 10 31 PM
Screen Shot 2023-04-20 at 1 10 48 PM
Screen Shot 2023-04-20 at 1 11 58 PM
Screen Shot 2023-04-20 at 1 11 43 PM

### CODE REVIEW

**Comment by StevenDufresne** [comment]
The inputs are looking a little small. Let's try to use more of the space around by reducing padding.

Screenshot 2023-04-20 at 2 48 10 PM

**Comment by outdoor2kode** [comment]
**Update Video**

https://user-images.githubusercontent.com/18050944/233280086-4cca34e5-8a6f-4d45-ba8e-1eebd60304e6.mov

@StevenDufresne how do you find the new look?

**Comment by StevenDufresne** [comment]
Looks better, but let's remove the padding on `.wporg-2fa__totp_setup-container` on mobile. That will align it with the others views which don't have that much extra padding.

Should we open another ticket for the "back" button being squished to the title?

**Comment by outdoor2kode** [comment]
**padding removed**

image image

**ticket for the "back" button being squished**: https://github.com/WordPress/wporg-two-factor/issues/128

**Comment by StevenDufresne** [comment]
Sorry for all the little picks, but things should expand full width in the container and only get constrained somewhere around `450px`.

## Screenshot

At about `370px`:

Screenshot 2023-04-24 at 11 19 10 AM

**Comment by outdoor2kode** [comment]
Not sure if this is what you had in mind?

https://user-images.githubusercontent.com/18050944/234390938-cf8548ef-7cd9-47bc-a73e-b4f28d1ab43b.mov

**Review by StevenDufresne — APPROVED** [review]

**Pull request merged**
